# Generated by Django 4.2.7 on 2025-07-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("authors", models.JSONField(default=list)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("file", models.FileField(upload_to="papers/")),
                ("file_size", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("abstract", models.TextField(blank=True)),
                ("keywords", models.JSONField(default=list)),
                ("doi", models.CharField(blank=True, max_length=100)),
                ("journal", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Paper",
                "verbose_name_plural": "Papers",
                "ordering": ["-created_at"],
            },
        ),
    ]
