# Generated by Django 5.1.1 on 2025-08-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="source",
            field=models.CharField(
                choices=[
                    ("arxiv", "ArXiv"),
                    ("semantic_scholar", "Semantic Scholar"),
                    ("pubmed", "PubMed"),
                    ("crossref", "Crossref"),
                    ("ieee", "IEEE"),
                    ("springer", "Springer"),
                    ("elsevier", "Elsevier"),
                    ("manual", "Manual Upload"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scrapingtask",
            name="source",
            field=models.CharField(
                choices=[
                    ("arxiv", "ArXiv"),
                    ("semantic_scholar", "Semantic Scholar"),
                    ("pubmed", "PubMed"),
                    ("crossref", "Crossref"),
                    ("ieee", "IEEE"),
                ],
                max_length=20,
            ),
        ),
    ]
