# Generated by Django 5.1.1 on 2025-08-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0004_alter_paper_source_alter_scrapingtask_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="arxiv_id",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paper",
            name="doi",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="pmid",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
