# Generated by Django 5.1.1 on 2025-08-04 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0005_remove_unique_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QASession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_name", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_sessions",
                        to="papers.paper",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Q&A Session",
                "verbose_name_plural": "Q&A Sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PaperQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("sources", models.JSONField(blank=True, default=list)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qa_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="papers.qasession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paper Question",
                "verbose_name_plural": "Paper Questions",
                "ordering": ["created_at"],
            },
        ),
    ]
