# Generated by Django 5.1.1 on 2025-08-04 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0006_qasession_paperquestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("methodology", "Methodology"),
                            ("results", "Results & Findings"),
                            ("limitations", "Limitations"),
                            ("future_work", "Future Work"),
                            ("background", "Background & Literature"),
                            ("impact", "Impact & Applications"),
                            ("data", "Data & Analysis"),
                            ("comparison", "Comparison & Evaluation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Question Template",
                "verbose_name_plural": "Question Templates",
                "ordering": ["category", "-usage_count"],
            },
        ),
        migrations.CreateModel(
            name="PaperTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#007bff", max_length=7)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paper Tag",
                "verbose_name_plural": "Paper Tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="paper",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="papers", to="papers.papertag"
            ),
        ),
        migrations.CreateModel(
            name="ResearchNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("is_private", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="papers.paper",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Note",
                "verbose_name_plural": "Research Notes",
                "ordering": ["-updated_at"],
            },
        ),
    ]
