# Generated by Django 4.2.7 on 2025-07-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaperAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abstract_summary", models.TextField()),
                ("main_findings", models.JSONField(default=list)),
                ("key_conclusions", models.JSONField(default=list)),
                ("study_design", models.TextField()),
                ("study_objectives", models.JSONField(default=list)),
                ("theoretical_framework", models.TextField()),
                ("research_question", models.TextField()),
                ("hypotheses_tested", models.JSONField(default=list)),
                ("intervention", models.TextField()),
                ("intervention_effects", models.TextField()),
                ("outcome_measured", models.JSONField(default=list)),
                ("measurement_methods", models.JSONField(default=list)),
                ("primary_outcomes", models.JSONField(default=list)),
                ("secondary_outcomes", models.JSONField(default=list)),
                ("statistical_significance", models.TextField()),
                ("effect_sizes", models.JSONField(default=list)),
                ("limitations", models.JSONField(default=list)),
                ("research_gaps", models.JSONField(default=list)),
                ("future_research", models.JSONField(default=list)),
                ("methodological_constraints", models.JSONField(default=list)),
                ("introduction_summary", models.TextField()),
                ("discussion_summary", models.TextField()),
                ("key_arguments", models.JSONField(default=list)),
                ("implications", models.JSONField(default=list)),
                ("related_papers", models.JSONField(default=list)),
                ("confidence_scores", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paper Analysis",
                "verbose_name_plural": "Paper Analyses",
            },
        ),
    ]
