# Generated by Django 4.2.7 on 2025-07-20 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("papers", "0001_initial"),
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperanalysis",
            name="paper",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis",
                to="papers.paper",
            ),
        ),
    ]
