# Generated by Django 5.1.1 on 2025-07-26 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0002_initial"),
        ("papers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analysissession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="analysissessionpaper",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="papers.paper"
            ),
        ),
        migrations.AddField(
            model_name="analysissessionpaper",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analysis.analysissession",
            ),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="papers",
            field=models.ManyToManyField(
                through="analysis.AnalysisSessionPaper", to="papers.paper"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="analysisresult",
            unique_together={("paper", "analysis_type")},
        ),
        migrations.AlterUniqueTogether(
            name="analysissessionpaper",
            unique_together={("session", "paper")},
        ),
    ]
